version: "3.8"
services:
  json-mock:
    image: zelejs/json-mock:lastest
    container_name: json-mock
    volumes:
      - "./src:/usr/src"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
